### ISSUE TITLE
Problem when executing any query but allPokemons

### ISSUE THREAD

**Issue by elC0mpa** [jgarrow/graphql-server-pokeapi#3]
First of all, I would like to thank you for creating this great API,I am using it to crreate an app for my portfolio
The problem is that, for example, I need to execute a query to get allTypes name, and this is the response I get:
![image](https://user-images.githubusercontent.com/53531665/129433365-fcf8651d-80cd-43bf-a7f7-5f6ba39d6fef.png)
it happens with other queries too, the one which has worken as I expected is getAllPokemon. Please let me knwo which solution could this have. Thanks in advance

**Comment by jgarrow** [comment]
Thanks for opening an issue! Looks like it was just an overlooked typo when I refactored some things a few months back. There is still a lingering issue with the `allMoves` query, but I'm going to close this since the `allTypes` query has been fixed. You can check out the fix at [this commit](https://github.com/jgarrow/graphql-server-pokeapi/commit/1818084bd992958a8f2195d4e69eacb0cc77fd30), if you're interested.
